version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: homex-api
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SHADOW_DATABASE_URL: ${SHADOW_DATABASE_URL}
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${PORT:-3001}
      JWT_SECRET: ${JWT_SECRET}
      AUTH_SECRET: ${AUTH_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CALLBACK_URL: ${GOOGLE_CALLBACK_URL}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GITHUB_CALLBACK_URL: ${GITHUB_CALLBACK_URL}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - homex-network

networks:
  homex-network:
    driver: bridge
