version: '3.8'
services:
  api:
    build: .
    container_name: nest-api
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules 
    command: npm run dev   
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: nest-db
    restart: always
    ports:
      - "5432:5432"
